Tradutor
schaiana/tradutor pull request #1
Opened 2019-11-18 21:14 UTC by schaiana

Olá!

Segue PR para revisão.

2019-11-20 14:11 UTC, mzr-certi requested changes

2019-11-20 14:11 UTC, mzr-certi commented on Dockerfile
> +RUN pip install -r requirements.txt
nitpick: essa ordem de instruções invalida as layers a cada mudança no ./src, não muito legal pra ambiente de dev

2019-11-20 14:11 UTC, mzr-certi commented on README.md
> +Ela desenvolvida utilizando Python e Flask.
nit: typo

2019-11-20 14:11 UTC, mzr-certi commented on README.md
> +* *start*: reponsável por executar a aplicação de maneira desacoplada ao terminal (cria um processo à parte);
nit: typo

2019-11-20 14:11 UTC, mzr-certi commented on testes/test_tradutor.py
> +    assert tradutor.valida_algarismo("0xFF") == False
é false mesmo? :P

2019-11-20 14:11 UTC, mzr-certi commented on src/tradutor.py
> +  100: "cem",
1XX é sempre traduzido assim?

2019-11-20 14:11 UTC, mzr-certi commented on testes/test_tradutor.py
> +    assert tradutor.valida_algarismo("$%#") == False
e se tiver alguns caracteres que são válidos no início/final, p.ex. espaço?

2019-11-20 14:11 UTC, mzr-certi commented on testes/test_tradutor.py
> +## Testes da função obtem_extenso
tem uns gaps bem grandes nesses testes que deixaram passar mta coisa errada

2019-11-20 14:11 UTC, mzr-certi commented on src/tradutor.py
> +                extenso = extenso_parcial + sufixo + extenso
e se nesse caso `cento, extenso_parcial` forem vazios quando já tiver alguma coisa no no extenso? eg. `-32000`

2019-11-20 14:11 UTC, mzr-certi commented on src/tradutor.py
> +    if (dezena != 0):
todos os casos onde a `dezena != 0` deveriam cair aqui mesmo?

2019-11-25 13:12 UTC, schaiana commented on testes/test_tradutor.py
> +    assert tradutor.valida_algarismo("$%#") == False
A ideia desse teste era só confirmar que caractere especial não é aceito.
É um requisito aceitar espaço no fim ou no início?
Da forma como foi estruturado, espaço antes e depois do número não é um formato válido.

2019-11-25 13:18 UTC, mzr-certi commented on testes/test_tradutor.py
> +    assert tradutor.valida_algarismo("$%#") == False
Requisito "formal" não é não

2019-11-25 13:44 UTC, schaiana commented on testes/test_tradutor.py
> +    assert tradutor.valida_algarismo("0xFF") == False
É para aceitar hexadecimal? :confused:

2019-11-25 13:46 UTC, mzr-certi commented on testes/test_tradutor.py
> +    assert tradutor.valida_algarismo("0xFF") == False
Depende, tecnicamente o formato nunca foi especificado

2019-11-25 13:46 UTC, schaiana commented on src/tradutor.py
> +  100: "cem",
Acho que o problema foi português por aqui. xD

2019-12-09 22:23 UTC, merged